[package]
name = "nsproxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
netns-rs = "0.1"

[profile.release]
lto = "fat"
